-- CREO SI NO EXISTE BASE DE DATOS 
CREATE DATABASE IF NOT EXISTS SQL_proyectoFinal;
-- SELECCIONO BASE DE DATOS A USAR
USE SQL_proyectoFinal;

-- CREO SI NO EXISTE LA TABLA CUENTAS
CREATE TABLE IF NOT exists CUENTAS(numeroCuenta INT AUTO_INCREMENT,
tipo VARCHAR(2) NOT NULL, 
moneda VARCHAR(4) NOT NULL,
saldo FLOAT NOT NULL,
 sobregiro FLOAT, PRIMARY KEY(numeroCuenta));

-- INSERTO DATOS DE PRUEBA 
INSERT INTO CUENTAS(tipo,moneda,saldo,sobregiro) VALUES('CC','U$S', 10,10),
('CC','U$S', 10,10),('CA','$', 10,NULL),('CC','$', 10,10),('CC','$', 10,10);


-- OBTENGO SALDO BANCARIO TOTAL 
SELECT SUM(saldo) FROM CUENTAS GROUP BY moneda;
-- OBTENGO SOBREGIRO TOTAL
SELECT SUM(saldo + ((sobregiro*saldo)/100)) 
FROM CUENTAS WHERE tipo ='CC' GROUP BY moneda;
-- ELIMINA TABLA 
DROP TABLE CUENTAS;

